name: Continous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        node-version: [22.22.0]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate up
          npm run test
        env:
          CI: true
          PGHOST: localhost
          PGHOST_TEST: localhost
          PGUSER: ${{ secrets.PGUSER_TEST }}
          PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
          PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
          PGPORT: 5432
          PGPORT_TEST: 5432
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
